# Generated by Django 6.0.3 on 2026-03-14 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference1', models.CharField(choices=[('CSE', 'B.Tech Computer Science Engineering'), ('CIVIL', 'B.Tech Civil Engineering')], max_length=10)),
                ('preference2', models.CharField(choices=[('CSE', 'B.Tech Computer Science Engineering'), ('CIVIL', 'B.Tech Civil Engineering')], max_length=10)),
                ('jee_score', models.FloatField(blank=True, null=True)),
                ('cuet_score', models.FloatField(blank=True, null=True)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('category', models.CharField(choices=[('General', 'General'), ('OBC', 'OBC'), ('SC', 'SC'), ('ST', 'ST'), ('EWS', 'EWS'), ('PWD', 'PWD')], max_length=20)),
                ('phone', models.CharField(max_length=15)),
                ('correspondence_address', models.TextField()),
                ('permanent_address', models.TextField()),
                ('is_jk_resident', models.BooleanField(default=False)),
                ('physics_marks', models.FloatField()),
                ('chemistry_marks', models.FloatField()),
                ('math_marks', models.FloatField()),
                ('max_marks', models.FloatField()),
                ('board_name', models.CharField(max_length=100)),
                ('school_name', models.CharField(max_length=200)),
                ('marksheet_10th', models.FileField(upload_to='documents/10th/')),
                ('marksheet_12th', models.FileField(upload_to='documents/12th/')),
                ('category_certificate', models.FileField(blank=True, null=True, upload_to='documents/category/')),
                ('domicile_certificate', models.FileField(blank=True, null=True, upload_to='documents/domicile/')),
                ('signature', models.ImageField(upload_to='signatures/')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
