# Generated by Django 6.0.3 on 2026-05-16 09:15

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='first_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='last_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='preference3',
            field=models.CharField(blank=True, choices=[('CSE', 'B.Tech Computer Science Engineering'), ('ECE', 'B.Tech Electronics and Communication Engineering'), ('CIVIL', 'B.Tech Civil Engineering')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='cuet_score',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='application',
            name='date_of_birth',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2000, 1, 1))]),
        ),
        migrations.AlterField(
            model_name='application',
            name='jee_score',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='application',
            name='preference1',
            field=models.CharField(choices=[('CSE', 'B.Tech Computer Science Engineering'), ('ECE', 'B.Tech Electronics and Communication Engineering'), ('CIVIL', 'B.Tech Civil Engineering')], max_length=10),
        ),
        migrations.AlterField(
            model_name='application',
            name='preference2',
            field=models.CharField(choices=[('CSE', 'B.Tech Computer Science Engineering'), ('ECE', 'B.Tech Electronics and Communication Engineering'), ('CIVIL', 'B.Tech Civil Engineering')], max_length=10),
        ),
    ]
