# Generated by Django 6.0.3 on 2026-05-16 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_studentprofile_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='preference3',
            field=models.CharField(choices=[('CSE', 'B.Tech Computer Science Engineering'), ('ECE', 'B.Tech Electronics and Communication Engineering'), ('CIVIL', 'B.Tech Civil Engineering')], default='CSE', max_length=50),
            preserve_default=False,
        ),
    ]
