# Generated by Django 6.0.3 on 2026-05-16 10:27

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_application_preference3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='preference3',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='middle_name',
        ),
        migrations.AlterField(
            model_name='application',
            name='date_of_birth',
            field=models.DateField(validators=[core.models.validate_dob_year]),
        ),
        migrations.AlterField(
            model_name='application',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='preference1',
            field=models.CharField(choices=[('CSE', 'B.Tech Computer Science Engineering'), ('CIVIL', 'B.Tech Civil Engineering'), ('ECE', 'B.Tech Electronics and Communication Engineering')], max_length=10),
        ),
        migrations.AlterField(
            model_name='application',
            name='preference2',
            field=models.CharField(choices=[('CSE', 'B.Tech Computer Science Engineering'), ('CIVIL', 'B.Tech Civil Engineering'), ('ECE', 'B.Tech Electronics and Communication Engineering')], max_length=10),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='date_of_birth',
            field=models.DateField(validators=[core.models.validate_dob_year]),
        ),
    ]
