# Generated by Django 6.0.3 on 2026-05-16 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_studentprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='preference3',
            field=models.CharField(blank=True, choices=[('CSE', 'B.Tech Computer Science Engineering'), ('CIVIL', 'B.Tech Civil Engineering'), ('ECE', 'B.Tech Electronics and Communication Engineering')], max_length=10, null=True),
        ),
    ]
