# Generated by Django 6.0.3 on 2026-05-18 08:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_application_preference3'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_round', models.CharField(choices=[('closed', 'Closed — No Applications Accepted'), ('round1_jee', 'Round 1 — JEE Mains 2026'), ('round2_cuet', 'Round 2 — CUET UG'), ('round3_board', 'Round 3 — 10+2 Board Percentage')], default='closed', help_text='Select the active admission round. Only one record should exist.', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Admission Round Control',
                'verbose_name_plural': 'Admission Round Control',
            },
        ),
        migrations.AddField(
            model_name='application',
            name='applied_round',
            field=models.CharField(default='round1_jee', help_text='Which round this application was submitted under.', max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='board_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Overall 10+2 board percentage (for Round 3 only).', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
