# Generated by Django 6.0.3 on 2026-05-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_admissionround_application_applied_round_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='aadhar_card',
            field=models.FileField(blank=True, null=True, upload_to='documents/aadhar/'),
        ),
        migrations.AddField(
            model_name='application',
            name='character_certificate',
            field=models.FileField(blank=True, null=True, upload_to='documents/character/'),
        ),
        migrations.AddField(
            model_name='application',
            name='entrance_roll_no',
            field=models.CharField(blank=True, help_text='JEE Roll No. / CUET Application No. as applicable.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='entrance_scorecard',
            field=models.FileField(blank=True, help_text='Upload JEE / CUET scorecard PDF or image.', null=True, upload_to='documents/scorecard/'),
        ),
        migrations.AddField(
            model_name='application',
            name='migration_certificate',
            field=models.FileField(blank=True, null=True, upload_to='documents/migration/'),
        ),
        migrations.AddField(
            model_name='application',
            name='passport_photo',
            field=models.ImageField(blank=True, null=True, upload_to='documents/photos/'),
        ),
    ]
