# Generated by Django 6.0.3 on 2026-05-18 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_application_aadhar_card_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeritListPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., Round 1 - CSE Merit List', max_length=200)),
                ('pdf_file', models.FileField(upload_to='merit_lists/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=True, help_text='Show on homepage?')),
            ],
            options={
                'verbose_name': 'Merit List PDF',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.RemoveField(
            model_name='application',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='application',
            name='status',
        ),
    ]
