# Generated by Django 6.0.3 on 2026-05-18 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_meritlistpdf_remove_application_remarks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='photo',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
