# Generated by Django 6.0.3 on 2026-05-18 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_application_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='entrance_roll_no',
        ),
        migrations.RemoveField(
            model_name='application',
            name='status',
        ),
    ]
