# Generated by Django 6.0.3 on 2026-05-11 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('user', 'User'), ('bot', 'Bot')], max_length=10)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_active', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CollegeKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('admissions', 'Admissions'), ('courses', 'Courses & Programs'), ('facilities', 'Campus Facilities'), ('fees', 'Fee Structure'), ('eligibility', 'Eligibility Criteria'), ('placement', 'Placement & Career'), ('hostel', 'Hostel & Accommodation'), ('contact', 'Contact & Location'), ('exam', 'Exams & Results'), ('general', 'General Information')], max_length=50)),
                ('topic', models.CharField(help_text="Short topic title e.g. 'CSE Fees 2025'", max_length=200)),
                ('information', models.TextField(help_text='Detailed information about this topic')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'College Knowledge',
                'verbose_name_plural': 'College Knowledge Base',
                'ordering': ['category', 'topic'],
            },
        ),
        migrations.CreateModel(
            name='ChatFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '👎 Not Helpful'), (2, '😐 Somewhat Helpful'), (3, '👍 Very Helpful')])),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chatbot.chatmessage')),
            ],
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.chatsession'),
        ),
        migrations.CreateModel(
            name='UnansweredQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
                ('frequency', models.IntegerField(default=1, help_text='How many times asked')),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolution_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatbot.chatsession')),
            ],
            options={
                'verbose_name': 'Unanswered Query',
                'verbose_name_plural': 'Unanswered Queries',
                'ordering': ['-frequency'],
            },
        ),
    ]
